#!/bin/sh

set -euo pipefail

echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

cat /etc/apk/repositories

apk --no-cache --allow-untrusted add \
    zlib-dev \
    chromium \
    xvfb \
    wait4ports \
    xorg-server \
    dbus \
    ttf-freefont \
    mesa-dri-swrast \
    grep \
    udev

tac /etc/apk/repositories | sed '1,3{d}' | tac | tee /etc/apk/repositories > /dev/null

chromium-browser --version
