#!/bin/sh

set -e

echo "Installing torus-cli"

get_version ()
{
    curl -s https://get.torus.sh/manifest.json | jq -r '.version'
}

download_binary ()
{
    VERSION="$1"

    cd /tmp
    curl -Lso torus-cli.zip "https://get.torus.sh/$VERSION/torus_${VERSION}_linux_amd64.zip"

    unzip torus-cli.zip > /dev/null 2>&1
    rm torus-cli.zip

    echo "/tmp/torus"
}

apk add --no-cache -t .deps curl jq unzip

TAG="$(get_version)"
BINARY="$(download_binary "$TAG")"

mv "$BINARY" /usr/bin
apk del .deps

torus -v

